# Triangular, pentagonal, and hexagonal
# Problem 45
# 
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle       Tn=n(n+1)/2       1, 3, 6, 10, 15, ...
# Pentagonal       Pn=n(3n−1)/2       1, 5, 12, 22, 35, ...
# Hexagonal       Hn=n(2n−1)       1, 6, 15, 28, 45, ...
# 
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.


class Integer
  def triangle
    return self*(self+1)/2
  end
  
  def pentagonal
    return self*(3*self-1)/2
  end
  
  def hexagonal
    return self*(2*self-1)
  end
end

triangles = []
triangleHash = Hash.new
pentagonals = []
hexagonals = []

0.upto(100000) do |x|
  triangles << x.triangle
  triangleHash[x.triangle] = x
  pentagonals << x.pentagonal
  hexagonals << x.hexagonal
end

p array = (triangles & pentagonals & hexagonals)
puts triangleHash[array.last]

