# Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
# 
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# 
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
# 
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk-Pj| is minimised; what is the value of D?
# 

beginning_time = Time.now

pentas = []

1.upto(10000) do |i|
  pentas << (i*(3*i-1))/2
end

0.upto(pentas.length-1) do |x|
  x.upto(pentas.length-1) do |y|
    if pentas.include?(pentas[x] + pentas[y])
      puts pentas[x].to_s + " " + pentas[y].to_s + " " + (pentas[y]-pentas[x]).to_s
      if pentas.include?(pentas[y] - pentas[x])
        puts pentas[x].to_s + " " + pentas[y].to_s + " " + (pentas[y]-pentas[x]).to_s + " DING "
      end
    end
  end
end


end_time = Time.now

puts "Time elapsed #{(end_time - beginning_time)} seconds"
      